apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sqs-consumer-keda-scaler
  namespace: sqs-consumer
  labels:
    app: sqs-consumer
    deploymentName: sqs-consumer
spec:
  scaleTargetRef:
    kind: Deployment
    name: sqs-consumer
  minReplicaCount: 1
  maxReplicaCount: 4
  pollingInterval: 10
  cooldownPeriod:  60
  triggers:
  - type: aws-sqs-queue
    metadata:
      queueURL: {{ .Values.queue_url }}
      queueLength: "10"
      awsRegion: {{ .Values.aws_region }}
      identityOwner: operator